config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'user/new'

  get 'user/index'

  get 'user/show'

  post 'user/create'
  
  get 'user/login'
  
  post 'user/login_process'
  
  get 'user/logout'

  root 'post#index'

  get 'post/index'

  get 'post/new'

  post 'post/create'

  get 'post/show/:id' => 'post#show'

  get 'post/create_comment/:id' => 'post#create_comment'

  get 'user/note'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index #게시글 보여주는 페이지
    @posts = Post.all
  end

  def new # 게시글 작성하는 form 있는 페이지
  end

  def create # 작성된 게시글 db에 넣는 액션
    
    Post.create(
      title: params[:title],
      content: params[:content],
      user_id: session[:user_id]
    )
    
    redirect_to '/'
  end

  def show # 한개의 게시글 보는 페이지
    @post = Post.find(params[:id])
    
    
    
  end

  def create_comment # 해당하는 글의 댓글 다는 액션
    Comment.create(
      post_id: params[:id],
      content: params[:content]
      )
    
    redirect_to :back
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def create
    User.create(
    email: params[:email],
    password: params[:password]
    )
    redirect_to '/'
  end
  
  def login
  end
  
  def login_process
    @user = User.find_by(email: params[:email])
    if @user
      if @user.password == params[:password]
        flash[:notice] = '로그인이 되었습니다.'
        session[:user_id] = @user.id
        redirect_to '/'
      else
        flash[:alert] = '패스워드가 잘못됬습니다.'
        redirect_to '/user/login'
      end
    else
      flash[:alert] = '회원 정보가 없습니다.'
      redirect_to '/user/new'
    end
  end
  
  def logout
    session.clear
    redirect_to '/'
  end
  
  def note
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/_flash.erb
<% if flash[:notice]%>  
<div class="alert alert-success" role="alert">
  <%= flash[:notice]%>
</div>
<% elsif flash[:alert]%>
  <div class="alert alert-danger" role="alert">
  <%= flash[:alert] %>
</div>
<%end%>  

app/views/layouts/_footer.erb
<footer class="footer">
    <div class="container">
        <span class="text-muted">Testing Now</span>
    </div>
</footer>

app/views/layouts/_navbar.erb
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="/">HomE</a>
  </li>
  <% if session[:user_id].nil? %>
  <li class="nav-item">
    <a class="nav-link" href="/user/new">회원 가입</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/user/login">로그인</a>
  </li>
  <%else%>
  <li class="nav-item">
    <a class="nav-link" href="/user/logout">로그아웃</a>
  </li>
  <%end%>
  <li class='nav-item'>
    <a class='nav-link' href='/user/note'>Note</a>
  </li>
</ul>

<!--<a href='/'>[홈으로]</a>-->
<!--<a href='/user/logout'>[로그아웃]</a>-->
<!--<a href='/user/new'>[회원가입]</a>-->
<!--<a href='/user/login'>[로그인]</a>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</head>
<body>
<%= render 'layouts/navbar'%>
<%= render 'layouts/flash'%>

<%= yield %>
<% render 'layouts/footer'%>
</body>
</html>

app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/post/create_comment.html.erb
<h1>Post#create_comment</h1>
<p>Find me in app/views/post/create_comment.html.erb</p>

app/views/post/index.html.erb
<!--<% @posts.each do |post|%>-->
<!--<p><%=post.id%> 번째 글 : <%=post.title%> <a href='/post/show/<%=post.id%>'> [보기]</a></p>-->
<!--<%end%>-->
<!--<a href='/post/new'>글쓰기</a>-->
<div class='container'>
    <div class='row'>
        <h1> 게시글 목록</h1>
    </div>
</div>

<div class='container'>
    <div class='row'>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>번호</th>
              <th>제목</th>
              <th>글쓴이</th>
              <th>작성일</th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post|%>
            <tr>
              <th scope="row"><%=post.id%></th>
              <td><a href='/post/show/<%=post.id%>'><%=post.title%></a></td>
              <td><%=post.user.email%></td>
              <!--<td><%=((Time.now - post.created_at)/60).round().to_s + ' 분전'%></td>-->
              <td><%=time_ago_in_words(post.created_at)%></td>
            </tr>
            <%end%>
          </tbody>
        </table>
    </div>
</div>

<div class='container'>
    <div class='row float-right'>
        <a href='/post/new'><button type="button" class="btn btn-primary">글쓰기</button></a>
    </div>
</div>

app/views/post/new.html.erb
<h1>게시글 작성</h1>
<!--<form action='/post/create'>-->
<!--    Title : <input type='text' name='title'><br>-->
<!--    Contetn: <input type='text' name='content'><br>-->
<!--    <input type='submit' value='OK'>-->
<!--</form>-->


<%= form_tag('/post/create', metthod:'post') do %>
  <%= label_tag(:title, '제목 : ')%>
  <%= text_field_tag(:title) %><br>
  <%= label_tag(:content,'내용 : ')%>
  <%= text_area_tag(:content)%><br>
  <%= submit_tag('글쓰기')%>
<%end%>

app/views/post/show.html.erb
<h1>게시글 보기</h1>
<p>제목 : <%=@post.title%></p>
<p>내용 : <%=@post.content%></p>

<!--<form action='/post/create_comment/<%=@post.id%>'>-->
<!--    <input type='text' name='content'>-->
<!--    <input type='submit' value='OK'>-->
<!--</form>-->
<%= form_tag("/post/create_comment/#{@post.id}", method: "get") do %>
  <%= label_tag(:content,'댓글 : ')%>
  <%= text_field_tag(:content)%>
  <%= submit_tag('댓글쓰기')%>
<%end%>

<% @post.comments.each do |c|%>
<p><%= c.content %></p>
<%end%>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/login.html.erb
<h1>로그인</h1>
<!--<form action='/user/login_process' method='post'>-->
<!--    email : <input type='text' name='email'><br/>-->
<!--    password : <input type='password' name='password'><br/>-->
<!--    <input type="hidden" name='authenticity_token' value='<%= form_authenticity_token%>'>-->
<!--    <input type='submit' value='회원가입'>-->
<!--</form>-->

<!--<%= form_tag("/user/login_process", method: "post") do %>-->
<!--  <%= label_tag(:email, 'Email : ')%>-->
<!--  <%= text_field_tag(:email) %><br>-->
<!--  <%= label_tag(:password, 'Password : ')%>-->
<!--  <%= text_field_tag(:password) %><br>-->
<!--  <%= submit_tag('Login')%>-->
<!--<%end%>-->
<div class='container'>
  <div class='row'>
    <div class = 'col-lg-3'>
    </div>
    <div class = 'col-lg-6 col-sm-12 col-12'>
      <form action='/user/login_process' method='post'>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" name='email' class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" name='password' class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token%>'>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
    <div class = 'col-lg-3'>
    </div>
  </div>
</div>

app/views/user/login_process.html.erb
<%=@user.password%>

app/views/user/new.html.erb
<h1>회원가입</h1>
<p>회원 가입 페이지</p>
<!--<form action='/user/create' method='post'>-->
<!--    email : <input type='text' name='email'><br/>-->
<!--    password : <input type='password' name='password'><br/>-->
<!--    <input type='submit' value='회원가입'>-->
<!--</form>-->


<%= form_tag("/user/create", method: "post") do %>
  <%= label_tag(:email, 'Email : ')%>
  <%= text_field_tag(:email) %><br>
    <%= label_tag(:password, 'Password : ')%>
  <%= password_field_tag(:password) %><br>
  <%= submit_tag('가입하기')%>
<%end%>

app/views/user/note.erb
<div class="row">
  <div class="col-sm-8">col-sm-8</div>
  <div class="col-sm-4">col-sm-4</div>
</div>
<div class="row">
  <div class="col-sm-4 col-4">1/3</div>
  <div class="col-sm-4 col-4">1/3</div>
  <div class="col-sm-4 col-4">1/3</div>
</div>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>